dist: xenial
sudo: required
services: docker
language: bash
addons:
    apt:
        sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu bionic main universe"
        packages:
            - debootstrap
            - qemu-user-static
env:
    global:
        - QEMU_VER=v4.2.0-2
        - DOCKER_REPO=pqclean/multiarch-debian-debootstrap
        - MIRROR=http://ftp.ports.debian.org/debian-ports/
    matrix:
        - ARCH=powerpc INCLUDE=wget QEMU_ARCH=ppc  SUITE=bullseye UNAME_ARCH=powerpc VERSION=bullseye
script:
    - sudo ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -s "$SUITE" -i "$INCLUDE" -o "$UNAME_ARCH"
after_success:
    - |
        if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && \
                docker push $DOCKER_REPO
        fi
